./: exe{confmsg}: {hxx cxx}{**} ixx{configuration}
{
  test = true
}

ixx{configuration}: in{configuration}

./: file{system.message.conf}
file{system.message.conf}@./: install = /etc/$config.lyrahgames_confmsg.config.subdir/$config.lyrahgames_confmsg.config.file_name

./: file{user.message.conf}
file{user.message.conf}@./: install = /etc/$config.lyrahgames_confmsg.config.subdir/