./: exe{confmsg}: {hxx cxx}{** -configuration_paths*installed}
{
  test = true
}

exe{confmsg}: cxx{configuration_paths_uninstalled}: for_install = false
cxx{configuration_paths_uninstalled}: in{configuration_paths}
{
  configuration_system_path = $src_root/etc
}

if ($install.root != [null])
{
  exe{confmsg}: cxx{configuration_paths_installed}: for_install = true
  cxx{configuration_paths_installed}: in{configuration_paths}
  {
    configuration_system_path = $config.confmsg.install.config
  }
}
